services:
  - type: web
    name: chollofitness-bot
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: AMAZON_ACCESS_KEY
        sync: false
      - key: AMAZON_SECRET_KEY
        sync: false
      - key: AMAZON_PARTNER_TAG
        sync: false
